### ISSUE TITLE
Validate API key button validates as Valid for deleted MultiSafePay Site.

### ISSUE THREAD

**Issue by Hexmage** [MultiSafepay/magento2-adminhtml#2]
Create a MSP test Site in the MSP panel.
Configure the api key in magento backend.
Go back to the MSP panel and delete the website.
Go to the magento config and click the validate button. You get a Valid result.

**Comment by vinodsowdagar** [comment]
Hi @Hexmage ,

Thanks for the report.

We'll look into this and come back to you later.

**Comment by vinodsowdagar** [comment]
@Hexmage ,

This should now automatically be fixed, can you try it again?
I'm closing this issue in the meantime, if there are any comments, please let us know and we will reopen the issue.
